on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.mediabit.ro
        username: ftp@mediabit.ro
        password: ${{ secrets.ftp_password }}
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          web/app/themes/mediabit/sources/**
          web/app/themes/mediabit/build/tools/**
